openapi: 3.0.1
info:
  title: UnderSounds - Servicio Usuarios
  version: 1.0.0
  description: |-
    Especificación OpenAPI para el servicio de usuarios de UnderSounds.
servers:
  - url: https://www.undersounds.com/api/v1/usuarios
tags:
  - name: users
    description: Operaciones sobre usuarios

paths:
  /users:
    get:
      tags:
        - users
      summary: Obtener un usuario.
      description: Devuelve la información del usuario autenticado.
      operationId: getUserByToken
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Usuario recuperado con éxito.
          content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
        '400':
          description: Información inválida o incompleta.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '401':
          description: Usuario no autenticado.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '500':
          description: Error interno.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'

    put:
      tags:
        - users
      summary: Actualizar un usuario.
      description: Devuelve la información actualizada del usuario autenticado.
      operationId: updateUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Usuario actualizado con éxito.
          content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
        '400':
          description: Información inválida o incompleta.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '401':
          description: Usuario sin permiso para actualizar el usuario.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '404':
          description: Usuario no encontrado.
        '500':
          description: Error interno.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'

    post:
      tags:
        - users
      summary: Crear un nuevo usuario.
      description: Registra un nuevo usuario en la plataforma.
      operationId: postUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: 'schemas/User.yaml'
      responses:
        '201':
          description: Usuario creado con éxito.
          content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
        '400':
          description: Información inválida o incompleta.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '500':
          description: Error interno.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'

  /users/{id}:
    get:
      tags:
        - users
      summary: Obtener un usuario por su ID.
      description: Devuelve la información del usuario especificado.
      operationId: getUserById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID del usuario a devolver.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Usuario recuperado con éxito.
          content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
        '401':
          description: Usuario sin permiso para acceder a la información del usuario.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '404':
          description: Usuario no encontrado.
        '500':
          description: Error interno.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'

    delete:
      tags:
        - users
      summary: Eliminar un usuario por su ID.
      description: Devuelve si el usuario ha sido eliminado con éxito.
      operationId: deleteUserById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID del usuario a eliminar.
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Usuario eliminado con éxito.
        '401':
          description: Usuario sin permiso para eliminar al usuario.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'
        '404':
          description: Usuario no encontrado.
        '500':
          description: Error interno.
          content:
            application/json:
              schema:
                $ref: 'schemas/Error.yaml'

# TODO: ¿Endpoints tanto para administradores como para usuarios /id y /?
# TODO: Se verá cómo se implementa al integrar OAuth.
  /login:
    get:
      tags:
        - users
      summary: Logs the user into the system
      description: Logs the user into the system
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: username to log in
          schema:
            type: string
        - name: password
          in: query
          description: user's password.
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid username/password