required:
  - name
  - photoUrls
type: object
properties:
  id:
    type: integer
    format: int64
    example: 10
  name:
    type: string
    example: "Camiseta"
  artist:
    $ref: 'Artist.yaml'
  photoUrls:
    type: array
    xml:
      wrapped: true
    items:
      type: string
      xml:
        name: photoUrl
  album:
    $ref: 'Album.yaml'
  description:
    type: string
    example: "Camiseta de Michael Jackson"
  price:
    type: integer
    format: int64
    example: 100
  status:
    type: string
    description: Estado del producto en la tienda
    enum:
      - disponible
      - pendiente
      - vendido