name: Publicar especificación OpenAPI en GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generar Servicio de Contenidos
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs/contenidos
          spec-file: servicio-contenidos.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      
      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v4